"""Trim uniform borders from exported PNGs and re-apply a small even margin.

Why this exists: draw.io's PNG export pads the image to the *page* rectangle, so a
diagram that does not exactly fill its page comes out with a large, asymmetric
white band (usually on the right and bottom). `--border` and `--crop` do not
reliably fix it, and the page size is rarely known exactly in advance when the
.drawio is generated by a script. Cropping to the real content bounding box after
export is deterministic and works regardless of page size or export flags.

Usage:
    python trim_png.py out/*.png
    python trim_png.py --pad 24 --bg 255,255,255 out/diagram.png

Requires Pillow, installed explicitly in an approved environment; see requirements.txt.
"""

from __future__ import annotations

import argparse
import sys

def trim(path: str, pad: int = 14, bg: tuple[int, int, int] = (255, 255, 255)) -> bool:
    """Crop `path` to its content bounding box, then re-pad by `pad` px. In place."""
    from PIL import Image, ImageChops

    if isinstance(pad, bool) or not isinstance(pad, int) or pad < 0:
        raise ValueError("padding must be a nonnegative integer")
    if len(bg) != 3 or any(isinstance(v, bool) or not isinstance(v, int) or not 0 <= v <= 255 for v in bg):
        raise ValueError("background must contain three integers in 0..255")
    with Image.open(path) as source:
        if source.format != "PNG":
            raise ValueError(f"not a PNG image: {path}")
        rgba = source.convert("RGBA")
        canvas = Image.new("RGBA", source.size, (*bg, 255))
        im = Image.alpha_composite(canvas, rgba).convert("RGB")
    background = Image.new("RGB", im.size, bg)
    bbox = ImageChops.difference(im, background).getbbox()
    if not bbox:
        raise ValueError(f"image is entirely background: {path}")

    content = im.crop(bbox)
    out = Image.new("RGB", (content.width + 2 * pad, content.height + 2 * pad), bg)
    out.paste(content, (pad, pad))
    out.save(path)
    print(f"trimmed {path} -> {out.width}x{out.height}")
    return True


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("paths", nargs="+", help="PNG files to trim in place")
    ap.add_argument("--pad", type=int, default=14, help="margin to re-add, px (default 14)")
    ap.add_argument("--bg", default="255,255,255",
                    help="background colour to trim, R,G,B (default 255,255,255)")
    args = ap.parse_args(argv)

    try:
        values = [int(v) for v in args.bg.split(",")]
    except ValueError:
        ap.error("--bg must be three integers in 0..255")
    if len(values) != 3 or any(not 0 <= v <= 255 for v in values):
        ap.error("--bg must be three integers in 0..255")
    if args.pad < 0:
        ap.error("--pad must be nonnegative")
    bg = (values[0], values[1], values[2])
    try:
        for p in args.paths:
            trim(p, args.pad, bg)
    except ModuleNotFoundError as exc:
        if exc.name != "PIL":
            raise
        print("ERROR: Pillow is required; install requirements.txt in an approved environment.", file=sys.stderr)
        return 1
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
